# 🚀 QUICK FIX SCRIPT - CRITICAL ENDPOINTS SECURITY
# Migra solo los 10 endpoints más críticos en 15 minutos

param(
    [switch]$DryRun = $false,
    [switch]$Force = $false
)

$ErrorActionPreference = "Stop"

# 🎯 CONFIGURACIÓN
$backendPath = "backend"
$backupSuffix = ".pre-security-fix"

# 📋 ENDPOINTS CRÍTICOS (Top 10 más usados)
$criticalEndpoints = @(
    "public/api/auth/secure-login.php",
    "public/api/candidates/save.php", 
    "public/api/candidates/save_v2.php",
    "public/api/cv/parse.php",
    "public/api/cv/ingest.php",
    "public/api/applications.php",
    "public/api/auth.php",
    "public/api/jobs.php",
    "public/api/chatbot.php",
    "public/api/send-email.php"
)

# 🛡️ SECURITY TEMPLATE
$securityTemplate = @"
<?php
/**
 * ⚡ AUTO-SECURED ENDPOINT
 * Generated by Quick Fix Script
 * Date: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
 */

// 🛡️ CRITICAL SECURITY GATES
require_once __DIR__ . '/../../src/Middleware/CsrfMiddleware.php';
require_once __DIR__ . '/../../src/Middleware/AuthMiddleware.php';
require_once __DIR__ . '/../../src/Utils/SecurityLogger.php';

// 🔒 MANDATORY SECURITY CHECKS
try {
    CsrfMiddleware::protect();
    AuthMiddleware::requireValidSession();
    SecurityLogger::logSecureAccess(__FILE__);
} catch (Exception `$e) {
    http_response_code(403);
    echo json_encode(['error' => 'Security validation failed', 'code' => 'SECURITY_ERROR']);
    exit;
}

// ✅ SECURITY PASSED - ORIGINAL CODE BELOW
// ============================================================================

"@

# 🟡 LEGACY MARKER TEMPLATE  
$legacyTemplate = @"
<?php
/**
 * @deprecated Will be removed in v2.0 - Use /api/v2/ endpoints
 * @legacy This endpoint lacks modern security features
 * @migration-priority LOW
 * @audit-date $(Get-Date -Format 'yyyy-MM-dd')
 */

// 🟡 LEGACY WARNING
if (!headers_sent()) {
    header('X-Legacy-Endpoint: true');
    header('X-Migration-Required: v2.0');
}

trigger_error(
    "LEGACY ENDPOINT ACCESSED: " . ($_SERVER['REQUEST_URI'] ?? __FILE__) . 
    " - Migration to v2.0 API recommended", 
    E_USER_DEPRECATED
);

// ============================================================================
// ORIGINAL LEGACY CODE BELOW
// ============================================================================

"@

function Write-Status {
    param([string]$Message, [string]$Color = "White")
    Write-Host $Message -ForegroundColor $Color
}

function Backup-File {
    param([string]$FilePath)
    
    $backupPath = $FilePath + $backupSuffix
    if (-not (Test-Path $backupPath)) {
        Copy-Item $FilePath $backupPath -Force
        Write-Status "  📦 Backup created: $backupPath" "DarkGray"
        return $true
    }
    return $false
}

function Apply-Security-Fix {
    param([string]$RelativePath)
    
    $fullPath = Join-Path $backendPath $RelativePath
    
    if (-not (Test-Path $fullPath)) {
        Write-Status "  ⚠️  File not found: $RelativePath" "Yellow"
        return $false
    }
    
    # Backup original
    Backup-File $fullPath
    
    # Read original content
    $originalContent = Get-Content $fullPath -Raw -ErrorAction SilentlyContinue
    
    if ($originalContent -match "CsrfMiddleware::protect|AuthMiddleware::require") {
        Write-Status "  ✅ Already secured: $RelativePath" "Green"
        return $true
    }
    
    if ($DryRun) {
        Write-Status "  🔍 [DRY-RUN] Would secure: $RelativePath" "Cyan"
        return $true
    }
    
    # Skip <?php tag if present
    if ($originalContent -match "^\s*<\?php") {
        $originalContent = $originalContent -replace "^\s*<\?php\s*", ""
    }
    
    # Apply security template
    $securedContent = $securityTemplate + $originalContent
    
    try {
        Set-Content $fullPath $securedContent -Encoding UTF8 -NoNewline
        Write-Status "  🛡️  SECURED: $RelativePath" "Green"
        return $true
    } catch {
        Write-Status "  ❌ Failed to secure: $RelativePath - $($_.Exception.Message)" "Red"
        return $false
    }
}

function Mark-As-Legacy {
    param([string]$FilePath)
    
    if (-not (Test-Path $FilePath)) {
        return $false
    }
    
    $content = Get-Content $FilePath -Raw -ErrorAction SilentlyContinue
    
    if ($content -match "@deprecated|@legacy|LEGACY ENDPOINT") {
        return $true # Already marked
    }
    
    if ($DryRun) {
        return $true
    }
    
    # Skip <?php tag if present
    if ($content -match "^\s*<\?php") {
        $content = $content -replace "^\s*<\?php\s*", ""
    }
    
    # Apply legacy marker
    $legacyContent = $legacyTemplate + $content
    
    try {
        Set-Content $FilePath $legacyContent -Encoding UTF8 -NoNewline
        return $true
    } catch {
        return $false
    }
}

# 🚀 MAIN EXECUTION
Write-Status "🛡️  CRITICAL ENDPOINTS SECURITY FIX" "Cyan"
Write-Status "   Target: $($criticalEndpoints.Count) critical endpoints" "White"

if ($DryRun) {
    Write-Status "   Mode: DRY-RUN (no changes will be made)" "Yellow"
} else {
    Write-Status "   Mode: LIVE EXECUTION" "Red"
    if (-not $Force) {
        $confirm = Read-Host "Continue? (y/N)"
        if ($confirm -ne "y") {
            Write-Status "❌ Aborted by user" "Red"
            exit 1
        }
    }
}

Write-Status "`n🔧 Processing critical endpoints..." "White"

$secured = 0
$skipped = 0

foreach ($endpoint in $criticalEndpoints) {
    Write-Status "📁 Processing: $endpoint" "White"
    
    if (Apply-Security-Fix $endpoint) {
        $secured++
    } else {
        $skipped++
    }
}

Write-Status "`n🟡 Marking remaining files as legacy..." "White"

# Mark all other PHP files as legacy (excluding already secured)
$allPhpFiles = Get-ChildItem -Path "$backendPath/public/api" -Recurse -Include "*.php" | Where-Object {
    $relativePath = $_.FullName -replace [regex]::Escape((Resolve-Path $backendPath).Path + "\"), ""
    $relativePath -notin $criticalEndpoints -and
    $_.FullName -notmatch "vendor/|_backup" -and
    $_.FullName -notmatch "\.pre-security-fix$"
}

$marked = 0
foreach ($file in $allPhpFiles) {
    if (Mark-As-Legacy $file.FullName) {
        $marked++
        if ($marked % 20 -eq 0) {
            Write-Status "  🟡 Marked $marked files as legacy..." "DarkGray"
        }
    }
}

# 📊 SUMMARY
Write-Status "`n" "White"
Write-Status "================================================================" "Cyan"
Write-Status "🎯 QUICK FIX COMPLETE" "Green"
Write-Status "================================================================" "Cyan"
Write-Status "🛡️  Critical endpoints secured: $secured" "Green"
Write-Status "⚠️   Endpoints skipped: $skipped" "Yellow" 
Write-Status "🟡 Legacy files marked: $marked" "DarkGray"
Write-Status "📦 Backups created with suffix: $backupSuffix" "DarkGray"

if (-not $DryRun) {
    Write-Status "`n🧪 RECOMMENDED NEXT STEPS:" "White"
    Write-Status "1. Run Cypress tests: npm run cypress:run" "White"
    Write-Status "2. Check CI pipeline: git push" "White"
    Write-Status "3. Monitor logs for LEGACY warnings" "White"
    Write-Status "4. Plan gradual migration of marked files" "White"
}

Write-Status "`n✅ Script completed successfully!" "Green"
